### PR TITLE
[Blog-tuning] LPS-97393

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1186. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/f13a90a4cc51~2...f13a90a4cc51)

**Pull request closed without merging**
