### PR TITLE
LPS-97264 Delete view permission checks from JSPs because they have been done before

### PR DESCRIPTION
**Pull request by dantewang**
Hi @4lejandrito This is a performance optimization. Could you review this pull from business logic point of view so that we don't break anything? Thanks! cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74866.

**Pull request closed without merging**
