### PR TITLE
LPS-99304 test for new behavior

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hey @4lejandrito 

I remove the onAfterCreate because tagging was called 2 times.
This doesn't solves the Google Drive Documents tagging. Better talk with Pablo before sending Brian.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Closing as discussed with @AliciaGarciaGarcia.

**Pull request closed without merging**
