### PR TITLE
LPS-93586 Test it.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/473. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/2863b755acbf~3...2863b755acbf)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/474. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/d341d2ba3fcf~7...d341d2ba3fcf)

**Pull request closed without merging**
