### PR TITLE
LPS-85848

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63638

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63650. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63651. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/34cc15ddf93e~1...34cc15ddf93e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
