### PR TITLE
LPS-92212 Delete google Drive Shorcut description cause duplicate information

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69699. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/874dc30c0c96~2...874dc30c0c96)

**Pull request closed without merging**
