### PR TITLE
[TS] LPS-112111

### PR DESCRIPTION
**Pull request by ChrisKian**
Rebased and sent to you since you've already looked into this issue.

From @jesseyeh-liferay:

> [LPS-112111](https://issues.liferay.com/browse/LPS-112111)
> 
> Displaying content from a deleted user in an Asset Publisher results in the content not displaying correctly, as well as "No User exists with the primary key XXXXX" errors in the logs. To resolve this issue, we implement a check to determine if the userId is valid before using it to retrieve the user.

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/492.

**Pull request closed without merging**
