### PR TITLE
LPS-110555 Redirect module: set URL fields with the proper type to be able to index them

### PR DESCRIPTION
**Pull request by achaparro**
Hi @4lejandrito,

I think you wanted URLs longer than 75 characters but defining them as Clob or unlimited varchar is problematic because they can't be part of database indexes. @kyle-miho found this issue because the creation of indexes failed in SQLServer and fix it defining URLs fields as URL type.

Please, review as soon as you can so we can add it in 7.3GA2 and we can avoid the creation of an upgrade process for this.

Thanks.

PD: Mucho ánimo con toda la sitación del virus allí, espero que podamos salir de ésta pronto. Un abrazo fuerte!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86528.

**Comment by 4lejandrito** [comment]
> Hi @4lejandrito,
> 
> I think you wanted URLs longer than 75 characters but defining them as Clob or unlimited varchar is problematic because they can't be part of database indexes. @kyle-miho found this issue because the creation of indexes failed in SQLServer and fix it defining URLs fields as URL type.
> 
> Please, review as soon as you can so we can add it in 7.3GA2 and we can avoid the creation of an upgrade process for this.
> 
> Thanks.
> 
> PD: Mucho ánimo con toda la sitación del virus allí, espero que podamos salir de ésta pronto. Un abrazo fuerte!

Gracias @achaparro. Lo mismo a vosotros por allí. Aquí en España gracias a Liferay no tenemos problema para estar en casa y trabajar, tenemos mucha suerte. Ánimo por allí también.

**Pull request closed without merging**
