### PR TITLE
LPS-83135  / LPS-83140 Remove Invitation/WYSIWYG data

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75033.

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75038. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/c72279590e7e~3...c72279590e7e)

**Pull request closed without merging**
