### PR TITLE
LPS-86435 Use sharing API to opt-in to sharing

### PR DESCRIPTION
**Pull request by Preston-Crary**
CC @adolfopa

@4lejandrito I think this is the simplest and best solution we can do.  Because of the API changes we're able to implement several performance improvements for sharing permission checking.  I think it's very reasonable for DL to consume sharing API.

I talked with @drewbrokke about the role idea in https://github.com/Preston-Crary/liferay-portal/pull/762 and after our discussion I think it's best to not go with that solution.

Sending back to you so you can rename SharingEntryDLFileEntryModelResourcePermissionRegistrarTest and make any other changes I might be missing.

Thanks!

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@Preston-Crary Thanks a lot for all the suggestions. It is really appreciated :-)

Could you share with us some of the reasons for discarding the permission based approach?  To us, It looks like a much simpler/cleaner solution than the current one.  Other than the (potentially) big number of rows in the permissions table, we don't really see any reason not to implement that.

Thanks!

**Comment by Preston-Crary** [comment]
@adolfopa at first it seems like the easiest solution.  But once you take into account hiding the roles in the control panel and how to do that it becomes less clear if it's a good option.

It brings up questions like: "should we make a new role type for this?" If we make a new role type we have to rewrite a lot of the permission framework to account for when and when not to use it.

Other option is to use a special prefix in the role name (like what you had), but then whatever we choose a customer might try to use for one of their roles and we have to do a (not like 'LIFERAY_SHARING_%') query everywhere in the users admin display.  This couples user admin to sharing heavily.

There's the problem of growing the Role table, which may cause performance problems later for things not even using sharing.

There's also a bigger risk of making a mistake and leaving behind invalid rows in the role table and opening up a new security vulnerabilities.

So after all of these thoughts, I think we should focus on making it easier to implement sharing by finding ways to shrink the sharing-document-library bundle.  If we can refactor sharing to have a one or two things that need to be implemented to enable sharing and improve performance we won't really need to do this through the role service. But we should only do that after we have a another sharing usage to make sure we don't abstract things the wrong way.

Hope that explains my reasoning well enough.

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
@Preston-Crary Makes sense. Thanks!

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/765. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/7b82942e1e37~4...7b82942e1e37)

**Pull request closed without merging**
