### PR TITLE
LPS-93172 ProcessUtil.execute is failing an no longer used.

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/7590. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/641977b4b53c~1...641977b4b53c)

**Pull request closed without merging**
