### PR TITLE
LPS-105643 add check to not show open Graph and custom open Graph on drafts, and layouts prototypes

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81929.

**Pull request closed without merging**
