### PR TITLE
LPS-105365 Avoid duplication of code and semantic versioninng changes

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
@4lejandrito Not sure about t[his commit ](https://github.com/4lejandrito/liferay-portal/pull/362/commits/d3c6ef605082558a89d9dad0c6bfafdc573f19e7) message ;-)

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83109. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/1c4e18dfb0e6~1...1c4e18dfb0e6)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83154. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/ad2e30b20b87~2...ad2e30b20b87)

**Pull request closed without merging**
