### PR TITLE
LPS-97569 These jsps only use the Locale from <liferay-theme:defineObjects />, replace it with PortalUtil.getLocale() to avoid the overhead of the tag

### PR DESCRIPTION
**Pull request by dantewang**
Hi @4lejandrito, I made this change because only the Locale from ThemeDisplay is currently used in these JSPs, while the <liferay-theme:defineObjects /> sets a lot more into the page context, which adds lots of overhead. Could you please review it in case it breaks anything? Thanks! cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/dantewang/liferay-portal/pull/1180. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/7636b29210d9~1...7636b29210d9)

**Pull request closed without merging**
