### PR TITLE
LPS-95732 Reduce unnecessary possible DB operation when MBThread is not question

### PR DESCRIPTION
**Pull request by dantewang**
cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/73350.

**Pull request closed without merging**
