### PR TITLE
LPS-73189 Mark module as deprecated

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/67. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/9e43af3~1...9e43af3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
