### PR TITLE
LPS-97123

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74779

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74824. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/6f6ade42cf23~4...6f6ade42cf23)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74825. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/9558f49cfc7b~4...9558f49cfc7b)

**Pull request closed without merging**
