### PR TITLE
LPS-109423 add TYPE_DEPOT to role check the deletion of roles on asset libraries

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85438. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/17fb3167563e~1...17fb3167563e)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85440. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/5255739d990c~2...5255739d990c)

**Pull request closed without merging**
