### PR TITLE
LPS-110834 listener message to add a scheduler task to delete not found entries

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/420. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/cb7aff4e21c2~5...cb7aff4e21c2)

**Pull request closed without merging**
