### PR TITLE
LPS-86298,LPS-86009,LPS-84799

### PR DESCRIPTION
**Pull request by Preston-Crary**
Hi @4lejandrito @adolfopa,

Being able to see how this is working was really helpful.  One thing that worries me is the changes in LPS-84799 look a little slow.  The biggest problem is there is no API to pass the FileVersion object back to the the DLAppService for deletion, so if we are deleting a lot of versions (for example when we first enable this feature) then we have to do a lot of refetching one-by-one.  I'm not saying you create a faster API in these tickets but I think it would be good to do before release.

I ran the two new tests and they are passing locally but I'm sending this back so you can review my changes.  

Thanks

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@Preston-Crary We've talked about this same issue, and we have plans to fix the asymmetry in the DM API before release; it is causing us a lot of headaches and is a source of problems for us.

Thanks a lot for looking into this!

**Comment by Preston-Crary** [comment]
@adolfopa great!

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65117. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
