### PR TITLE
LPS-98654 Avoid NPE

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @robertoDiaz,

I am on vacation please resend to @adolfopa.

Thanks!

**Comment by IstvanD** [comment]
Hi @robertoDiaz

I would like to ask if you have sent the pull request to @adolfopa?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
@adolfopa is on PTO, and he'll come back this Monday.

I'll send it to him this day.

**Comment by IstvanD** [comment]
Thank you for the answer, @robertoDiaz !

**Comment by robertoDiaz** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/77134?email_source=notifications&email_token=AAU2EFXL7ZTKPSMZBGOU5ZTQFJQZPA5CNFSM4IM3JZNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4SIJJI#issuecomment-522486949

**Comment by robertoDiaz** [comment]
See https://github.com/adolfopa/liferay-portal/pull/1065

**Pull request closed without merging**
