### PR TITLE
[TECHNICAL-SUPPORT] LPS-84230

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @brianikim

> https://issues.liferay.com/browse/LPS-82717 fixed the issue of a fileEntry not being downloaded with the correct extension when you create a fileEntry without any files uploaded first, then update the said fileEntry with an actual file upload.
> 
> The issue addressed with this PR addresses the scenario in which the correct extension is not used for the download when you create a fileEntry with a file uploaded, then update the said fileEntry by changing the name of the file to have a different extension. The file will be downloaded with the different extension rather than the extension of the file originally uploaded.
> 
> The reason this issue occurs is because our current checks for mimeType and extension are flawed in that we do not consider the possibility that files can be updated without any files being uploaded. Thus, extension and mimeType are fetched from the title rather than existing fileEntry extensions and mimeTypes.
> 
> The fix is to make sure that we grab the existing fileEntry extension and mimeType even when no files are uploaded during an update.
> 
> Please let me know if you have any questions. Thanks.

/cc @sergiogonzalez

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Hi @jonathanmccann ,

I am currently on vacation. I'll be back on Monday and get on with this as soon as I can. 

Regards

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62097. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/34d0613~3...34d0613) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
