### PR TITLE
LPS-108249 Remove dead css and fix vertical align on infobar

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84691. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/c90d4a677ad4~2...c90d4a677ad4)

**Pull request closed without merging**
