### PR TITLE
LPS-69117 Wiki version can be compared to itself

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @4lejandrito 

As I mentioned in https://github.com/robertoDiaz/liferay-portal/pull/496#issuecomment-263512818 I send this pull request to you.
I appreciate if you take a look at it.

Thank you,
István

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @IstvanD, I will take a look at this today :)

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Hi @IstvanD,

I have been testing your code. It works fine but there is an edge case where it doesn't behave as it should. When there are only 2 versions (1.0 and 1.1 for instance) the value of those versions is not displayed because of the way the icon-menu tag works. If there are 0 icons it won't display therefore the title (the current selected version) won't be displayed either. Please check the screenshot below.

image

Can you take a look at it?

**Comment by IstvanD** [comment]
Hey @4lejandrito 

Thank you for pointing that out, I never thought of that.

With using the `icon` tag instead of the `icon-menu` tag when the number of versions <= 2 I managed to solve this problem.

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45151. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
