### PR TITLE
LPS-109249 Fix Language dnd include direction calc

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86086. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/679885d1e1a0~1...679885d1e1a0)

**Pull request closed without merging**
