### PR TITLE
DELETE Enable new ratings in blogs for testing porpouses

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
citr

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/309. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/a0828fb648df~6...a0828fb648df)

**Pull request closed without merging**
