### PR TITLE
LPS-105197 Tests for languages component

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
@4lejandrito Please change the LPS of the last two commits, its LPS-107277

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83799. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/93c06f7fb609~3...93c06f7fb609)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83809. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/4492e4183463~4...4492e4183463)

**Pull request closed without merging**
