### PR TITLE
LPS-111941 Check chained Redirections

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:retest:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/aliciagarciagarcia/liferay-portal/pull/48. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/a9096f840054~9...a9096f840054)

**Pull request closed without merging**
