### PR TITLE
LPS-101617 Update hook usage in layout-content-page-editor-web

### PR DESCRIPTION
**Pull request by wincent**
Hi @4lejandrito (cc: @p2kmgcl).

I extracted the `useIsMounted()` hook into a common location. I've already sent this over to Brian [here](https://github.com/brianchandotcom/liferay-portal/pull/78396) along with the change to update segments-experiment-web but wanted to give you a heads up. Please let me know if anything looks off here.

### CODE REVIEW

**Comment by wincent** [comment]
Also sent https://github.com/andresfulla/liferay-portal/pull/151 over to @andresfulla for similar review.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Looks and works 👍 . 

Thansk @wincent!

**Pull request closed without merging**
