### PR TITLE
LPS-107251 Remove Liferay.provide is useless without dependencies

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/129. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/3859210f162c~3...3859210f162c)

**Pull request closed without merging**
