### PR TITLE
LPS-94166 added a SPACE between number and unit

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/patriciajeanperez/liferay-portal/pull/188. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/4ec27639c638~1...4ec27639c638)

**Pull request closed without merging**
