### PR TITLE
LPS-110947 Control NPE

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/419. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/901d39511429~1...901d39511429)

**Pull request closed without merging**
