### PR TITLE
LPS-115586 Passing only InfoFormValues

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@JorgeFerrer I will rebase and resend once https://github.com/ealonso/liferay-portal/pull/2996#issuecomment-647464623 is merged.

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
The changes look good to me. Feel free to send it directly once rebased (you'll need to adapt the code to the rename InfoFormValues to InfoItemFieldValues)

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/308.

**Pull request closed without merging**
