### PR TITLE
LPS-90033 Fix minor bug with a very big and mocked test

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69577. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/ac89060db867~1...ac89060db867)

**Pull request closed without merging**
