### PR TITLE
LPS-102541 add logic to delete from management toolbar to a new actionCommand

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80879. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/d7132ebad007~10...d7132ebad007)

**Pull request closed without merging**
