### PR TITLE
LPS-107727 Reload the iframe when the item list changes (after an upload or when an image is edited)

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/297. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/de1f48e7c256~1...de1f48e7c256)

**Pull request closed without merging**
