### PR TITLE
LPS-106810 Autogenerated

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:seo

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83102. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/cef8ad6cf701~3...cef8ad6cf701)

**Pull request closed without merging**
