### PR TITLE
[TS] LPS-104076 Avoid NPE in case there is no DL

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-104076

Regression caused by LPS-91884, in case you remove DL processor in portal-ext.properties (dl.file.entry.processors property) a NPE is thrown during *DLPreviewRendererProviderFactory activation

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @jorgediaz-lr,

@4lejandrito is on PTO until next week. Please send me any PR you have.

Thanks!

**Comment by jorgediaz-lr** [comment]
Hi @adolfopa 
I sent this PR to him because he implemented **LPS-91884**. That LPS causes this one.

Resent to https://github.com/adolfopa/liferay-portal/pull/1137

**Comment by 4lejandrito** [comment]
Thanks guys!

**Pull request closed without merging**
