### PR TITLE
LPS-111054 - Add test to Ratings Like

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/165. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/ad2e6f5ad1fd~3...ad2e6f5ad1fd)

**Pull request closed without merging**
