### PR TITLE
LPS-104952 Optimize hooks

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:seo

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/112. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/bdbfd0d6e4a7~8...bdbfd0d6e4a7)

**Pull request closed without merging**
