### PR TITLE
LPS-94820 added Test fot testing checkout & checking with restricted number of versions

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72434. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/7641d2d63bc2~2...7641d2d63bc2)

**Pull request closed without merging**
