### PR TITLE
LPS-122730

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@4lejandrito one more thing (and then go ahead and send to Brian)

We have class names `ViewSharedAssetsMVCRenderCommand` and `ViewSharingEntryMVCRenderCommand`
Both names use `mvc.command.name=/*.*_view_sharing_*`

You decide what to name it, but let's make sure the mvc.command.name matches the class name

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Hi @hhuijser,

Thanks for catching that. My bad. It is actually not needed, `/` is enough.

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/991.

**Pull request closed without merging**
