### PR TITLE
LPS-101158 AutoFS

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/aliciagarciagarcia/liferay-portal/pull/25. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/3e9f273ab5b0~5...3e9f273ab5b0)

**Pull request closed without merging**
