### PR TITLE
[Performance Tuning]LPS-96213

### PR DESCRIPTION
**Pull request by tinatian**
Hi @4lejandrito ,

This was found when tuning Document Library, when uploading a file, an AssetDisplayPageEntry is added into database with layoutPageTemplateEntryId=0, but we did not have any layoutPageTemplateEntry in database which id is 0, I think we should not add the entry here and made this change.

Please correct me if there is special reason we are doing this.

cc @shuyangzhou

Thanks.
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Hi @tinatian,

I am afraid these changes break the intended behaviour. A display page can be configrued in 3 different ways:

1. **Specific:** The selected display page will be used for the file entry all the time.
2. **Default:** The default display page (if any) will be used for the file entry. If there is no default display page, it will be rendered by the documents and media portlet as usual.
3. **None:** No display page will be used (not even the default one), the file entry will be rendered by the documents and media portlet as usual.

Cases 1 and 2 must be explicitly stored in the database (AssetDisplayPageEntry). If no entry is found the expected behaviour is not to use display pages at all (case 3).

The way that class works is that it stores the "Default" by default 😄 . With your changes display pages will never work unless users explicitly configure them for each file. 

I am inclined to think that case 2 should be the default when no entry is found in the database but I had a chat with @jkappler and they have done it this way on purpose. Maybe he or @pavelsavinov can give you further insight on this.

Thanks anyway @tinatian.

**Comment by tinatian** [comment]
Hi @4lejandrito 
Thanks for the detailed explanation!

I have some questions:
1) is there always a "Default" display page? 
As long as I can see, it is NOT. It means if the user is not going to use display page at all, you are still going to have tons of entries created in your database, which is indeed a waste.
2) Why we allow to config as "Default" if there is no "Default" at all?
We should not allow a setting to "Default" if you do not have any LayoutPageTemplateEntry at all, which means you are not going to use display page.

According to current logic, when I:
1) Start bundle from empty database
2) Add Document and Media to page
3) Click upload file and in the upload page, you will see:
https://issues.liferay.com/secure/attachment/314067/Screenshot%20at%202019-05-29%2014-32-29.png

It is saying you are going to use default, but there is no default at all.

Tina.

**Comment by 4lejandrito** [comment]
Hi @tinatian,

1. You are right and I agree that we will be creating tons of wasted rows. 
2. That's a good point too. This might be to cover the case when the default display page is created after uploading the files so that the users don't have to go and manually enable the default for each already uploaded file.

As I said in my previous comment I also think that the default behaviour should add no extra rows and should use the default display page (if any) unless NONE is manually selected. However this seems to be a product decision made by the WCM team. 

If you really think this should change I recommend you talk to @jkappler and handle it directly with them.

Thanks for your feedback on this.

**Comment by tinatian** [comment]
Thanks @4lejandrito ! I sent out an email about this.

Tina.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
