### PR TITLE
LPS-86344

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64220. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/0bfe58157b31~2...0bfe58157b31) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
