### PR TITLE
LPS-111941 add test for update references

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/489. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/2316f1fe4ac6~11...2316f1fe4ac6)

**Pull request closed without merging**
