### PR TITLE
LPS-99173 Use BlogsEntryServiceUtil

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi @robertoDiaz 

Could you please review this pull request?

Since `BlogsEntryServiceUtil.getGroupUserEntries()` might return more than 1 result, I modified the condition checks.

Thank you and best regards,
István

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @robertoDiaz,

I am on vacation please resend to @adolfopa.

Thanks!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I would like to ask if you have sent the pull request to @adolfopa?

Thank you and best regards,
István

**Comment by robertoDiaz** [comment]
The same as https://github.com/4lejandrito/liferay-portal/pull/317

**Comment by IstvanD** [comment]
Thank you for the answer, @robertoDiaz !

**Comment by robertoDiaz** [comment]
See https://github.com/adolfopa/liferay-portal/pull/1064

**Pull request closed without merging**
