### PR TITLE
LPS-104369 Add custom behavior for canonicalURLField

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:seo

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/aliciagarciagarcia/liferay-portal/pull/28. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/fb0ab6507e0b~3...fb0ab6507e0b)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81451. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/ff3978b62694~3...ff3978b62694)

**Pull request closed without merging**
