### PR TITLE
LPS-84112

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62093. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/f3fe974~1...f3fe974) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
