### PR TITLE
LPS-97376 message of "no permission" on messages without, but letting user access to the messages if the messages have permision for it

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/aliciagarciagarcia/liferay-portal/pull/13. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/36cfe79ed775~1...36cfe79ed775)

**Pull request closed without merging**
