### PR TITLE
LPS-93309 Validate name on update

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70727. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/43ec70557092~2...43ec70557092)

**Pull request closed without merging**
