### PR TITLE
LPS-135132 Enabling check in site settings doesn't work when it's unchecked in Instance settings > Site scope

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-135132](https://issues.liferay.com/browse/LPS-135132).<br/><br/>Hi @4lejandrito, will you please review this change to see if it fixes your issue\? It contains the same string replacement logic, but used in a different spot. The main difference here is that if we determine that a configuration has not been saved at the current scope, we discard the found configuration. Please let me know if you have any question or concerns. Thanks!<br/><br/>/cc @pei-jung @alee8888

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @drewbrokke,

The issue seems to be fixed with these changes too. 

However I've noticed that when there is something saved in `Instance Settings`, the URL generated in `Site Settings` still contains the instance settings PID which I am not sure if can be problematic (this also happened with my fix). See the URL at the bottom of the screenshot.

Screenshot 2021-07-09 at 12 33 13

If that's not a problem I would say this is good to go.

Thanks!

**Comment by drewbrokke** [comment]
@4lejandrito got it, thanks for the heads up. I think since it's an existing issue, I'll plan to fix it in a separate pull. This does make me want to re-think how we handle passing `pid`s around the portlet, so I appreciate you bringing this to my attention.

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
@patriciajeanperez is this a related failure?

**Comment by patriciajeanperez** [comment]
ci:forward

**Pull request closed without merging**
