### PR TITLE
LPS-97456 Fix _getAssetEntry in view_entries.jspf, pass the previous AssetEntry as parameter

### PR DESCRIPTION
**Pull request by dantewang**
cc @tinatian

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See https://github.com/dantewang/liferay-portal/pull/1179#issuecomment-506244907.

**Pull request closed without merging**
