### PR TITLE
LPS-91447 Build Lang

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72321. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/dce0b334c61e~1...dce0b334c61e)

**Pull request closed without merging**
