### PR TITLE
LPS-111053 Add more average score test

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/87523. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/595ccdfc3537~2...595ccdfc3537)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/446. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/595ccdfc3537~2...595ccdfc3537)

**Pull request closed without merging**
