### PR TITLE
LPS-104952 SF

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:seo

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/113. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/b6af0281fa1f~2...b6af0281fa1f)

**Pull request closed without merging**
