### PR TITLE
LPS-96625 SF

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74419. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/d60a9a6e7475~3...d60a9a6e7475)

**Pull request closed without merging**
