### PR TITLE
[TECHNICAL-SUPPORT] 	LPS-70145 Escape all of the reserved characters according to RFC3986

### PR DESCRIPTION
**Pull request by moltam89**
Hi Alejandro,

this issue is about escaping special characters in Wiki Page titles, because it's possible that the **VirtualHostFilter** fails when there is a special character in the title.

I think a more general solution would be to create a new column ( e.g. urlTitle)  in the wikipage table, like what we have for Web Contents, so we could normalize the title properly.

However, as it would require schema modification, I don't think that we could handle it as a bug and backport it to 7.

Therefore I looked for alternative solutions and found **WikiEscapeUtil**, where a few special characters are already handled.
I extended the list, according to [RFC3986](https://tools.ietf.org/html/rfc3986#section-2.2).

Could you please review my changes?

Thanks!
Tamás

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Hi @moltam89 , this pull does not fix the issue. I have been debugging and the problem seems to be [here](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L170).
The URL is not even recognized as a friendly URL therefore your code is never reached for the URL containing the exclamation mark.
Please let us know if you need further assistance

**Comment by moltam89** [comment]
Hi @4lejandrito ,

I'm not sure about the steps you have taken, could you please write it down?

My fix should replace the **!** (and all the reserved characters), so there won't be any invalid characters in the URL, therefore the code in **VirtualHostFilter** won't fail.

It should work the same as for example with a **?** in the title, which is already handled in **WikiEscapeUtil**.

Thanks,
Tamás

**Comment by 4lejandrito** [comment]
Hi @moltam89, 

I have followed the steps you described in the ticket, but I tried from the command line like this (to avoid chrome escaping the exclamation mark):
```
curl http://testhost:8080/testpage/-/wiki/Main/testWikiPage\!
```
And that URL never reaches the code in **WikiEscapeUtil**. Instead it goes through [that if statement I mentioned](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L170) and is not identified as a friendly URL thus the server returns a 404. The code in **VirtualHostFilter** runs before the one in **WikiEscapeUtil**.

I have done further testing and:
* `http://testhost:8080/testpage/-/wiki/Main/testWikiPage!` - 404
* `http://testhost:8080/testpage/-/wiki/Main/testWikiPage%21` - WORKS
* `http://testhost:8080/testpage/-/wiki/Main/testWikiPage%3CEXCLAMATION%3E` - WORKS

Shouldn't it show the same article (testWikiPage!) in all of the cases above?

Please let me know if I am doing something wrong.

**Comment by moltam89** [comment]
Hi @4lejandrito ,

maybe my steps are not clear enough, I put the URL only as an example.

The fix only works when we are using a link generated by the Wiki portlet.

Without the fix, the Wiki portlet generates URLs like this:
**/wiki/Main/testWikiPage%21**
It won't cause any problems yet, as the question mark is escaped.

However, it seems fragile to me. E.g. if we use the previously mentioned URL in Firefox, it will automatically unescape it, which can lead to an error.

After the fix however, Wiki portlet will generate URLs like this:
**/wiki/Main/testWikiPage<EXCLAMATION**

I think generally we shouldn't have special characters in URLs, **WikiEscapeUtil** already handles a few of them, I can't see why we shouldn't handle all of special ones.

**Comment by 4lejandrito** [comment]
Ok, I understand. So what I described in my previous comment is the expected behaviour, right? We won't support unescaped special characters like `!`.

If that is the case I will move this forward to master. 

Can you confirm?

**Comment by moltam89** [comment]
Yeah, I'd say that's the expected.

Thanks!

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46252. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
