### PR TITLE
LPS-78173

### PR DESCRIPTION
**Pull request by jonathanmccann**
@4lejandrito 

I went ahead and applied the same permission checking to the secondary subscribe checkbox since it seems it performs the same action as the first subscribe link. Please let me know if you don't think it needs to be applied there.

Thanks.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62216. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/a68df14~4...a68df14) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62217. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/6950f93~3...6950f93) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
