### PR TITLE
LPS-101158 create a jspf to add the front part of the languages

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Pull request submitted to https://github.com/aliciagarciagarcia/liferay-portal/pull/24. [See changes here.](https://github.com/4lejandrito/liferay-portal/compare/9457cc9905db~4...9457cc9905db)

**Pull request closed without merging**
